Add output directory option to `archive extract`
Unity-Technologies/UnityDataTools pull request #9
Opened 2023-09-20 21:16 UTC by davschne-unity

Specifications:
* Optional arguments are added to `UnityDataTools archive extract` to set the output directory to <directory path>:
    * long form: `--output-path <directory path>`
    * short form: `-o <directory path>`
* If the directory specified doesn't exist, the tool should create it.
* If no output directory is specified, the tool should extract the archive to a directory called `archive` in the current directory.
* When extracting an archive, its internal file structure (i.e. subdirectories) should be preserved, not flattened.

2023-09-21 17:39 UTC, francis-page requested changes

2023-09-21 17:39 UTC, francis-page commented on UnityDataTool/Program.cs
> +                CopyFile("/" + node.Path, $"{outputFolder}/{node.Path}");
Does it work in Windows? Wouldn't it be better to use Path.Combine for the destination path?

2023-09-21 20:25 UTC, davschne-unity commented on UnityDataTool/Program.cs
> +                CopyFile("/" + node.Path, $"{outputFolder}/{node.Path}");
It does work in Windows. I can use `Path.Combine`, though, if that's better C# style.

2023-09-25 17:14 UTC, francis-page approved these changes

2023-09-25 17:14 UTC, merged